name: docker-build-publish
run-name: "docker-build-publish: ${{ github.ref_name }}"

on:
  push:
    branches: ["main"]
    paths:
      - "pkg/**"
      - "cmd/**"
      - "internal/**"
      - "build/package/**"
      - ".github/workflows/docker-build-publish.yaml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  docker-build-push:
    name: docker-build-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: github-checkout
        uses: actions/checkout@v6

      - name: docker-login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker-meta
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=sha-,format=short

      - name: docker-build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/package/platform-mcp/Dockerfile
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
